version: '3'
services:
    short-linker:
        build: .
        image: short-linker
        command: short-linker
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - short-linker
